# Pure Python vs. Numpy - Lab

## Introduction 

Numpy, Scipy and Pandas libraries provide a significant increase in computational efficiency with complex mathematical operations as compared to Python's built in arithmatic functions.  In this lab we shall calculate and compare the processing speed required for calculating a dot product both using basic arithmatic operations in Python and Numpy's `.dot()` method. 

## Objectives
You will be able to:
* Compare the performance of high dimensional matrix operations in Numpy vs. pure Python

## Problem
> **Write a routine to calculate the dot product between two 200 x 200 dimensional matrices using:**

> **a) Pure Python**

> **b) Numpy's `.dot()`**


### Create two 200 x 200 matrices in Python and fill them with random values using `np.random.rand()` 

In [2]:
# Compare 200x200 matrix-matrix multiplication speed
import numpy as np

# Set up the variables
k = 200
A = np.random.randint(11, size=(k,k))
B = np.random.randint(11, size=(k,k))

### Pure Python

* Initialize an zeros filled numpy matrix with necessary rows and columns for storing result. 
* In Python Calculate the dot product using the formula 
![](formula.png)
* Use Python's `timeit` library to calculate the processing time. 
* [Visit this link](https://www.pythoncentral.io/time-a-python-function/) for an indepth explanation on how to time a function or routine in python. 

**Hint**: Use nested for loop for accessing, calculating and storing each scalar value in the result matrix.

In [3]:
print(A)
print('----------')
print(B)
A.shape    #  A[row][column]

[[ 1  5  6 ...  2  8  6]
 [ 9  0  7 ...  0  5  1]
 [ 8  7  1 ...  7  9  8]
 ...
 [ 9  7  7 ...  1  4  3]
 [ 7  9  8 ...  0 10  1]
 [ 3  3  0 ...  1  0  7]]
----------
[[ 2  5  4 ...  9  3  5]
 [ 9  0  1 ...  8 10  0]
 [ 5  4  9 ...  0  0  8]
 ...
 [ 4  4  9 ...  0  9  0]
 [ 0  0  3 ...  6  8  8]
 [ 7  4  3 ...  4  0 10]]


(200, 200)

In [4]:
A @ B

array([[4840, 4656, 5030, ..., 4952, 4618, 5290],
       [4802, 4624, 5179, ..., 5264, 4777, 5438],
       [4588, 4479, 4822, ..., 5003, 4616, 5346],
       ...,
       [4717, 4603, 4949, ..., 5407, 4491, 5184],
       [4489, 4426, 4770, ..., 5240, 4585, 5017],
       [4678, 4594, 4802, ..., 5167, 4412, 5156]])

In [8]:
import timeit

def matrix_mult_python(A=A, B=B):
    return A @ B
        
matrix_mult_python(A, B)
# Start the timer
time_spent = timeit.timeit(matrix_mult_python, number=10)

print('Pure Python Time:', time_spent, 'sec.')

Pure Python Time: 0.07524758810177445 sec.


## Numpy 
Set the timer and calculate the time taken by `.dot()` function for multiplying A and B 


In [12]:
# start the timer
start = None

# Matrix multiplication in numpy
def numpy_dot(A=A, B=B):
    #return np.dot(A,B)
    return A.dot(B)

time_spent = timeit.timeit(numpy_dot, number=10)
print('Numpy Time:', time_spent, 'sec.')

Numpy Time: 0.07975384779274464 sec.


### Your comments 

```
```

## Summary

In this lab, we performed a quick comparison between calculating a dot product in numpy vs python built in function. We saw that Numpy is computationally much more efficient that Python code due to highly sophisticated implementation of Numpy source code. You are encouraged to always perform such tests to fully appreciate the use of an additional library in Python. 